### PR TITLE
fix: spread filelist into array to satisfy useUpload

### PR DESCRIPTION
**Pull request by kevcjones**
Related to #5 

This seems like the simplest change to keep the code mostly as is and avoids the 'throw Missing Files' error.

### CODE REVIEW

**Comment by farnabaz** [comment]
When do you have missing files error? Is there any specific situation?

Passing an input file into the upload function is also fine, since the function checks for the `files` property and use it if its a file-list

Are you using any specific device or browser? I tested chrome, firefox and safari and in all cases `form.image` works as expected

**Comment by kevcjones** [comment]
I'll test it again, i was just following the first install and run guide and ran into an immediate issue, and the issue was structure of the data if i recall from the form not being as expected. The 'missing files' part was just the throw when it failed to resolve the upload 'File' object.

**Comment by kevcjones** [comment]
Browser was latest Chrome on OSX latest

**Comment by atinux** [comment]
Well I tried and got no error though.

Do you have a screen recording of the error?

**Pull request closed without merging**
